### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by LouisCAD** [shivasurya/materialsteppers#1]
Hi!
I saw several things you can improve in your library. The first, is following the java and android naming convention.
Java classes should begin with an uppercase letter ([`mobileStepperSimple`](https://github.com/shivasurya/materialsteppers/blob/master/materialsteppers/src/main/java/ivb/com/materialstepper/mobileStepperSimple.java) should be `SimpleMobileSteppers` or `MobileSteppersSimple`), and fields (member variables) should have a "m" prefix.
For example, if you have `int step` as a field, it should be `int mStep` in Android, avoiding having to add `this.` prefix to differentiate local variables from members visually.

**Comment by shivasurya** [comment]
added in 0.0.2 commit - if any issue or enhancement!just feel free to reopen
