### ISSUE TITLE
Converted host activity to fragment but inside 2nd child layout take long height in bottom

### ISSUE THREAD

**Issue by dilip90** [shivasurya/materialsteppers#12]

**Comment by shivasurya** [comment]
please describe more with screenshot
thanks

**Comment by dilip90** [comment]
Hi thanks for reply,

your simpleMobileStepper.java is extending Activity but i need to perform this on Fragment so  i have created clone of simpleMobileStepper.java custome class which extend fragment . my problem is when i add three fragment in List<Class> then there is automatically long height added in second fragment.

**Comment by shivasurya** [comment]
Respected,
I've utilized scrollview to show fragments in order to flexible for all layouts.
May be I can see workaround for this issue and get to you back.
Stay tuned, new stable release yet to rollout in a week.
