### ISSUE TITLE
Is it possible to put ToolBar view in the stepper activity?

### ISSUE THREAD

**Issue by VioletGiraffe** [shivasurya/materialsteppers#13]
Or other views, for that matter? I took a quick look at the example, and it doesn't seem to define the activity layout XML at all.

**Comment by shivasurya** [comment]
i'll look into that! the thing is i couldn't spend time to add more features.any contributions are accepted :+1:

**Comment by shivasurya** [comment]
Currently I'm not supporting any views or view group inside may be I can add Toolbar and you may extend to use it in activity.
Feel free to reopen.
