### ISSUE TITLE
Potential memory leaks

### ISSUE THREAD

**Issue by LouisCAD** [shivasurya/materialsteppers#2]
Hi!
In [this class](https://github.com/shivasurya/materialsteppers/blob/master/materialsteppers/src/main/java/ivb/com/materialstepper/mobileStepperSimple.java), you keep a reference to all fragments. If Android needs more memory for your app, it will destroy Fragments, but the garbage collector won't be able to free memory until it kills your Activity entirely because you hold a reference in a List. You should use FragmentStatePagerAdapter and save instance state to manage your fragments instead. You can see my Popular Movies project to see how I implemented FragmentStatePagerAdapter (which doesn't properly save instance state for now though) ;)

**Comment by shivasurya** [comment]
sure i'm always happy to accept pull request ! can you fork and reduce memory leaks.i'm working on next component with progress bar,even though my college project ends i would like to see making this library more mature enough and helpful for others.
please contribute if you can, i will through see through the issues

**Comment by shivasurya** [comment]
added FragmentStatePagerAdapter - 0.0.2 ! feel free to reopen !
