### ISSUE TITLE
Some fields can be local

### ISSUE THREAD

**Issue by LouisCAD** [shivasurya/materialsteppers#3]
Hi,
It's me again! :)
In [this class](https://github.com/shivasurya/materialsteppers/blob/master/materialsteppers/src/main/java/ivb/com/materialstepper/mobileStepperSimple.java), you hold the `FragmentManager` in a member variable (applies also for other fields such as `FragmentTransaction`, but use it only in one method. You shouldn't ignore Android Studio warnings and check your code quality, especially for a public library which could be used in third-party production apps. Keep me tuned for updates! :)

**Comment by shivasurya** [comment]
obeyed all warnings in android studio - and committed 0.0.2 ! feel free to reopen

**Comment by LouisCAD** [comment]
Awesome for all the enhancements, I'm going to take another look at your library :)
