### ISSUE TITLE
Back button showing on first fragment

### ISSUE THREAD

**Issue by PrashantMangale** [shivasurya/materialsteppers#4]
Hey hi Shivasurya,
It's a great job. It is very useful for me. I am working on one android application and using your library i am trying register user to our system. But have some small issue in this library is that when you are on first fragment 'Back' button is visible. 
I have checked your code for that next and back button. You already added code for it means you have checked that current fragment is more than 0 or not. When current fragment is >0 then all are fine but when you are on 1st fragment then you have to disable that 'Back' button.
It quite confusing for user that something is still before than first screen.
You can check this issue on your given application. I am also adding screenshot for it with red circle. Please check and update your library as fast as possible.
And thanks giving such nice library. Great job. :+1: 
![screenshot_20160116-235608](https://cloud.githubusercontent.com/assets/7066962/12373814/3dfca9f2-bcad-11e5-9c8b-9ae06dc8af5b.png)

**Comment by shivasurya** [comment]
first of all thanks for giving a feedback :) 
it's good to hide back button on first fragment,will add this to my to-do list - for temporary fix you can just use visibility method - may be i can accept Pull request :)

**Comment by PrashantMangale** [comment]
But I am not able to change your library code for visibility. If possible
can you update for this issue.
Or on how many days you will update this library?

Thanks,
Prashant Mangale

**Comment by shivasurya** [comment]
i'm working on this - testing and optimized some performance issues will be commiting by this weekend for sure.

**Comment by PrashantMangale** [comment]
Okey great. Thanks. I will wait till weekend.

**Comment by tamsir** [comment]
Yeah, really great JOB

**Comment by PrashantMangale** [comment]
Thanks man. I have just checked you have committed code on yesterday. It's a great job. I will check your new update and will let you know if i want change. Keep it up. It will be very useful for me.

**Comment by shivasurya** [comment]
sry! i haven't commited the code yet sir! will soon push it,the code is ready.

**Comment by PrashantMangale** [comment]
Ohk. But I have seen 23rd in last commit to this.
No problem. I hope you will update code today. So that I can check out
tomorrow.

**Comment by tamsir** [comment]
Hello shivasurya,
Any news about the back button?
thanks.

**Comment by shivasurya** [comment]
yeah! i was attending hackathon event couldn't commit the codebase - the Test Repo is here(i made it public and implemented with new features,bug fix and backbutton feature too) https://github.com/shivasurya/stepperTest - implemented two types of steppers 
- simpleMobileStepper 
- progressMobileStepper - soon i'll merge the code base

thanks for the patience guys.please bare with me :|

**Comment by PrashantMangale** [comment]
Ok no problem. I will check features with test repo and will look for live
code. All the best for hackathon event. Thanks for making changes so fast.
Its a great job. Thanks !

**Comment by tamsir** [comment]
Okay Shivasurya.
Thanks and good luck for the hackathon.

**Comment by shivasurya** [comment]
won 2nd prize in hackathon :) thanks guys - [link](https://www.instagram.com/p/BA_7FMvvgoq/?taken-by=sshivasurya)

committed 0.0.2 added some new feature and added back button fix too :) feel free to comment and use it.i'll update readme.md soon

**Comment by PrashantMangale** [comment]
Ohk great work. Congratulation man. You deserve for it. Keep it up.
We will check new update and let you know for changes if any.

**Comment by shivasurya** [comment]
feel free to reopen !

**Comment by tamsir** [comment]
Congratulation for the second prize. Good job.

**Comment by shivasurya** [comment]
thanks! any feedback to improve ? please share

**Comment by PrashantMangale** [comment]
Hello Shivsuya,

Well, its a good job. I don't have any issues right now.
If i face any problem will let you know. Till that you can add your ideas
to change some look and feel.
Overall is good. You have reduced my extra work.
Thanks a lot.

**Comment by tamsir** [comment]
Hello Shivsuya,
I try it in a multi step form for a survey and I have one problem.
The variable I define in the last fragment step was not send to the onStepperCompleted().
I receive the variable of all the fragment but not the variable of the last fragment.

**Comment by shivasurya** [comment]
Please share code! And explain more sir

**Comment by tamsir** [comment]
Okay, I have modify the structure but I'll send an example in the week.
In you example medicaApp do you receive all the variable of the 6 step in the onStepperCompleted() method?

**Comment by shivasurya** [comment]
Any examples ?
Btw you can use sqlitedb or shared preference to store intermediate values to process

**Comment by tamsir** [comment]
Hello shivasurya.
Yes I have used preferences to save variables. But the variable saved in
the last fragment always return null. I think that something wen't wrong.

**Comment by shivasurya** [comment]
if possible share your code - let me give it a try.

**Comment by tamsir** [comment]
Finally the client prefer a stepper with state visible on the top. I move
to this library https://github.com/fcannizzaro/material-stepper with Tab
Stepper view.
I'll see I can get the first version of my code to share with you.

2016-03-06 13:17 GMT+00:00 s.shivasurya notifications@github.com:

**Comment by shivasurya** [comment]
that's great ! :) that repo seems better than this

**Comment by tamsir** [comment]
Your Repo is good too.

2016-03-06 14:22 GMT+00:00 s.shivasurya notifications@github.com:
