### ISSUE TITLE
right to left layout

### ISSUE THREAD

**Issue by rezazarchi** [shivasurya/materialsteppers#5]
hello.
please add right to left layout to your library.
Thank you...

**Comment by shivasurya** [comment]
Will make it as enhancement - and will try to resolve by 0.0.3 version. Any general feedback?

**Comment by rezazarchi** [comment]
thanks for your Answering. 
it has another problem. I can't use object of class in my project. it just accepts classes.  
when i want to make a lot of steps with same type, I have to make class for each of them!

**Comment by shivasurya** [comment]
Hello,

Just pass the class as much times you want - actually I've implemented
array list to have class names alone.

Because to reduce the memory consumption and overhead. Assume there are lot
of objects in heap while you create and pass it as parameter,it takes huge
heap memory.

So to overcome,I've implemented viewpager state adapter which can
dynamically create object when it needs and destroy therefore it saves
memory.

Don't worry your data are saved by savedinstance state and be sure you have
given appropriate ID to your widget view to save the instance state.

For further queries post it,let me try to resolve. Share is care.

**Comment by shivasurya** [comment]
Hey shivasurya/materials,

Discover high quality jobs and connect with recruiters on LinkedIn.

- Shivasurya

Accept invite: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=dCBa3Agh&invitationId=6179689445013413890&trk=eml-invite_guest-invite_guest-103-india_a&trkEmail=eml-invite_guest-invite_guest-103-india_a-null-0%7Eisuk85b3%7Ehx



You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-isuk85b3-hx&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQElS_GWZgL7hgAAAVcKq-ezON8j2pwdT3ABifyTCF0Pnrk2byIAqyqUCTugRi-NS1qX1e2DpbzajmOIxKAiUXfvGq5_nWSJ3wmnK6ZtqzcxDIWAVIkqO11S1Vhq3tOOgCRqh4_2r4BzN4CIM5qGI4hnx-U1eSdtmrs7XfFCF0gPEjoSW2HDRnA0c8Mqhnf_jHmz&eid=0-isuk85b3-hx


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-isuk85b3-hx&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by shivasurya** [comment]
Shivasurya S would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=dCBa3Agh&invitationId=6179689445013413890&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-%7E9jk67i%7Eit2ng8ed%7Ehp

View Shivasurya S&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=dCBa3Agh&invitationId=6179689445013413890&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-%7E9jk67i%7Eit2ng8ed%7Ehp





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-9jk67i-it2ng8ed-hp&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=-9jk67i-it2ng8ed-hp&loid=AQF2ZYU_GTmP6gAAAVcotPjXtuT6F0M7kCkifNTzXrTa2qMvJ1Uc5VUnp5eqGCakMPA1PiAVPB6UP2VpvFynDtd8O2IMi8eqfZV4tVYB6YSShwEhJiJoyPEc5JgHFs9TL8Jm47Had7nrz6IXzEUCCUwUgTd4ItAh-rd4X3iRhlJGP5T8_MamFH5d7GEVlHFWJuOJ

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-9jk67i-it2ng8ed-hp&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by shivasurya** [comment]
Hi ,

Shivasurya S would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=dCBa3Agh&invitationId=6179689445013413890&trk=eml-second_guest_reminder_01-hero-120-accept_text&trkEmail=eml-second_guest_reminder_01-hero-120-accept_text-null-%7E9jk67i%7Eitcvgj16%7E8j

View Shivasurya S&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=dCBa3Agh&invitationId=6179689445013413890&trk=eml-second_guest_reminder_01-hero-3-profile_text&trkEmail=eml-second_guest_reminder_01-hero-3-profile_text-null-%7E9jk67i%7Eitcvgj16%7E8j





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-9jk67i-itcvgj16-8j&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=122&m=unsub&ts=HTML&eid=-9jk67i-itcvgj16-8j&loid=AQFGCUCxKIm9HQAAAVdMsWlPaC-znjxbRZTyL2j6pNxeJBpxkaBAryLjuJ-wegTFPWFphsNw4YEnoAeryZ_WFGmhygT70Mv0N631ouIF6Pe3TS-vwLpvp-v_1ys8IFzU2tKQD1xjxV6njstdsQfCrTvzqvUlKhv_dSrJP_sOMAIp009QvSKWuUIRv3X7E-mrVZhE

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-9jk67i-itcvgj16-8j&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
